
// export const typography = EStyleSheet.create({
// 	displayLarge: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "3.56rem",
// 		lineHeight: "4rem",
// 		letterSpacing: "-0.015625rem",
// 	},
// 	displayMedium: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "2.8125rem",
// 		lineHeight: "3.25rem",
// 		letterSpacing: 0,
// 	},
// 	dispaySmall: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "2.25rem",
// 		lineHeight: "2.75rem",
// 		letterSpacing: 0,
// 	},

// 	headlineLarge: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "2rem",
// 		lineHeight: "2.5rem",
// 		letterSpacing: 0,
// 	},
// 	headlineMedium: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "1.75rem",
// 		lineHeight: "2.25rem",
// 		letterSpacing: 0,
// 	},
// 	headlineSmall: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "1.5rem",
// 		lineHeight: "2rem",
// 		letterSpacing: 0,
// 	},
// 	titleLarge: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "1.375rem",
// 		lineHeight: "1.75rem",
// 		letterSpacing: 0,
// 	},
// 	titleMedium: {
// 		fontFamily: "Roboto",
// 		fontWeight: "500",
// 		fontSize: "1rem",
// 		lineHeight: "1.5rem",
// 		letterSpacing: "0.009375rem",
// 	},
// 	titleSmall: {
// 		fontFamily: "Roboto",
// 		fontWeight: "500",
// 		fontSize: "0.875rem",
// 		lineHeight: "1.25rem",
// 		letterSpacing: "0.00625rem",
// 	},
// 	bodyLarge: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "1rem",
// 		lineHeight: "1.5rem",
// 		letterSpacing: "0.03125rem",
// 	},
// 	bodyMedium: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "0.875rem",
// 		lineHeight: "1.25rem",
// 		letterSpacing: "0.015625rem",
// 	},
// 	bodySmall: {
// 		fontFamily: "Roboto",
// 		fontWeight: "400",
// 		fontSize: "0.75rem",
// 		lineHeight: "1rem",
// 		letterSpacing: "0.025rem",
// 	},
// 	labelLarge: {
// 		fontFamily: "Roboto",
// 		fontWeight: "500",
// 		fontSize: "0.875rem",
// 		lineHeight: "1.25rem",
// 		letterSpacing: "0.00625rem",
// 	},
// 	labelMedium: {
// 		fontFamily: "Roboto",
// 		fontWeight: "500",
// 		fontSize: "0.75rem",
// 		lineHeight: "1rem",
// 		letterSpacing: "0.03125rem",
// 	},
// 	labelSmall: {
// 		fontFamily: "Roboto",
// 		fontWeight: "500",
// 		fontSize: "0.6875rem",
// 		lineHeight: "1rem",
// 		letterSpacing: "0.03125rem",
// 	},
// 	textUppercase: { textTransform: "uppercase" },
// })


import { StyleSheet } from "react-native"

const baseFontSize = 16 // Default font size in pixels

export const typography = StyleSheet.create({
	displayLarge: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 3.56,
		lineHeight: baseFontSize * 4,
		letterSpacing: -0.015625 * baseFontSize,
	},
	displayMedium: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 2.8125,
		lineHeight: baseFontSize * 3.25,
		letterSpacing: 0,
	},
	dispaySmall: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 2.25,
		lineHeight: baseFontSize * 2.75,
		letterSpacing: 0,
	},
	headlineLarge: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 2,
		lineHeight: baseFontSize * 2.5,
		letterSpacing: 0,
	},
	headlineMedium: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 1.75,
		lineHeight: baseFontSize * 2.25,
		letterSpacing: 0,
	},
	headlineSmall: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 1.5,
		lineHeight: baseFontSize * 2,
		letterSpacing: 0,
	},
	titleLarge: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 1.375,
		lineHeight: baseFontSize * 1.75,
		letterSpacing: 0,
	},
	titleMedium: {
		fontFamily: "Roboto",
		fontWeight: "500",
		fontSize: baseFontSize * 1,
		lineHeight: baseFontSize * 1.5,
		letterSpacing: 0.009375 * baseFontSize,
	},
	titleSmall: {
		fontFamily: "Roboto",
		fontWeight: "500",
		fontSize: baseFontSize * 0.875,
		lineHeight: baseFontSize * 1.25,
		letterSpacing: 0.00625 * baseFontSize,
	},
	bodyLarge: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 1,
		lineHeight: baseFontSize * 1.5,
		letterSpacing: 0.03125 * baseFontSize,
	},
	bodyMedium: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 0.875,
		lineHeight: baseFontSize * 1.25,
		letterSpacing: 0.015625 * baseFontSize,
	},
	bodySmall: {
		fontFamily: "Roboto",
		fontWeight: "400",
		fontSize: baseFontSize * 0.75,
		lineHeight: baseFontSize * 1,
		letterSpacing: 0.025 * baseFontSize,
	},
	labelLarge: {
		fontFamily: "Roboto",
		fontWeight: "500",
		fontSize: baseFontSize * 0.875,
		lineHeight: baseFontSize * 1.25,
		letterSpacing: 0.00625 * baseFontSize,
	},
	labelMedium: {
		fontFamily: "Roboto",
		fontWeight: "500",
		fontSize: baseFontSize * 0.75,
		lineHeight: baseFontSize * 1,
		letterSpacing: 0.03125 * baseFontSize,
	},
	labelSmall: {
		fontFamily: "Roboto",
		fontWeight: "500",
		fontSize: baseFontSize * 0.6875,
		lineHeight: baseFontSize * 1,
		letterSpacing: 0.03125 * baseFontSize,
	},
	textUppercase: { textTransform: "uppercase" },
})
